# Generated by scripts/gen_proto.py from src/shipinfer/launch/proto/shard.proto -- DO NOT EDIT.
# Regenerate with:  python scripts/gen_proto.py
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from shipinfer.launch.proto import shard_pb2 as shipinfer_dot_launch_dot_proto_dot_shard__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in shipinfer/launch/proto/shard_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ShardStub(object):
    """The control surface a shard process exposes to its launcher.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ready = channel.unary_unary(
                '/shipinfer.launch.v1.Shard/Ready',
                request_serializer=shipinfer_dot_launch_dot_proto_dot_shard__pb2.ReadyRequest.SerializeToString,
                response_deserializer=shipinfer_dot_launch_dot_proto_dot_shard__pb2.ReadyReply.FromString,
                _registered_method=True)
        self.UpdateTopology = channel.unary_unary(
                '/shipinfer.launch.v1.Shard/UpdateTopology',
                request_serializer=shipinfer_dot_launch_dot_proto_dot_shard__pb2.TopologyRequest.SerializeToString,
                response_deserializer=shipinfer_dot_launch_dot_proto_dot_shard__pb2.TopologyReply.FromString,
                _registered_method=True)
        self.AddCamera = channel.unary_unary(
                '/shipinfer.launch.v1.Shard/AddCamera',
                request_serializer=shipinfer_dot_launch_dot_proto_dot_shard__pb2.AddCameraRequest.SerializeToString,
                response_deserializer=shipinfer_dot_launch_dot_proto_dot_shard__pb2.AddCameraReply.FromString,
                _registered_method=True)
        self.RemoveCamera = channel.unary_unary(
                '/shipinfer.launch.v1.Shard/RemoveCamera',
                request_serializer=shipinfer_dot_launch_dot_proto_dot_shard__pb2.RemoveCameraRequest.SerializeToString,
                response_deserializer=shipinfer_dot_launch_dot_proto_dot_shard__pb2.RemoveCameraReply.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/shipinfer.launch.v1.Shard/Health',
                request_serializer=shipinfer_dot_launch_dot_proto_dot_shard__pb2.HealthRequest.SerializeToString,
                response_deserializer=shipinfer_dot_launch_dot_proto_dot_shard__pb2.HealthReply.FromString,
                _registered_method=True)
        self.Stats = channel.unary_unary(
                '/shipinfer.launch.v1.Shard/Stats',
                request_serializer=shipinfer_dot_launch_dot_proto_dot_shard__pb2.StatsRequest.SerializeToString,
                response_deserializer=shipinfer_dot_launch_dot_proto_dot_shard__pb2.StatsReply.FromString,
                _registered_method=True)
        self.Drain = channel.unary_unary(
                '/shipinfer.launch.v1.Shard/Drain',
                request_serializer=shipinfer_dot_launch_dot_proto_dot_shard__pb2.DrainRequest.SerializeToString,
                response_deserializer=shipinfer_dot_launch_dot_proto_dot_shard__pb2.DrainReply.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/shipinfer.launch.v1.Shard/Stop',
                request_serializer=shipinfer_dot_launch_dot_proto_dot_shard__pb2.StopRequest.SerializeToString,
                response_deserializer=shipinfer_dot_launch_dot_proto_dot_shard__pb2.StopReply.FromString,
                _registered_method=True)


class ShardServicer(object):
    """The control surface a shard process exposes to its launcher.
    """

    def Ready(self, request, context):
        """Polled by the parent after the spawn: the first reply that arrives is the readiness
        signal, because a process that answers has finished importing and bound its port.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTopology(self, request, context):
        """Install the chain this shard runs, and the device-sharing it must honour.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddCamera(self, request, context):
        """Start one camera on this shard. A refusal is `accepted = false`, never an exception.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveCamera(self, request, context):
        """Stop and forget one camera.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """What state this shard is in. Safe against a concurrent removal.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stats(self, request, context):
        """Counters an operator would page on.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Drain(self, request, context):
        """Stop reading cameras, let in-flight work finish. Returns the abandonment count.
        A shard reports `draining` while the call is in flight and `drained` once it returns;
        only a later UpdateTopology makes it take cameras again. Serialised with Stop on the
        shard, so two of these cannot be inside the camera set at once.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Drain, then stop the executor. Idempotent: a second Stop reports 0 abandoned.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShardServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ready': grpc.unary_unary_rpc_method_handler(
                    servicer.Ready,
                    request_deserializer=shipinfer_dot_launch_dot_proto_dot_shard__pb2.ReadyRequest.FromString,
                    response_serializer=shipinfer_dot_launch_dot_proto_dot_shard__pb2.ReadyReply.SerializeToString,
            ),
            'UpdateTopology': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTopology,
                    request_deserializer=shipinfer_dot_launch_dot_proto_dot_shard__pb2.TopologyRequest.FromString,
                    response_serializer=shipinfer_dot_launch_dot_proto_dot_shard__pb2.TopologyReply.SerializeToString,
            ),
            'AddCamera': grpc.unary_unary_rpc_method_handler(
                    servicer.AddCamera,
                    request_deserializer=shipinfer_dot_launch_dot_proto_dot_shard__pb2.AddCameraRequest.FromString,
                    response_serializer=shipinfer_dot_launch_dot_proto_dot_shard__pb2.AddCameraReply.SerializeToString,
            ),
            'RemoveCamera': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveCamera,
                    request_deserializer=shipinfer_dot_launch_dot_proto_dot_shard__pb2.RemoveCameraRequest.FromString,
                    response_serializer=shipinfer_dot_launch_dot_proto_dot_shard__pb2.RemoveCameraReply.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=shipinfer_dot_launch_dot_proto_dot_shard__pb2.HealthRequest.FromString,
                    response_serializer=shipinfer_dot_launch_dot_proto_dot_shard__pb2.HealthReply.SerializeToString,
            ),
            'Stats': grpc.unary_unary_rpc_method_handler(
                    servicer.Stats,
                    request_deserializer=shipinfer_dot_launch_dot_proto_dot_shard__pb2.StatsRequest.FromString,
                    response_serializer=shipinfer_dot_launch_dot_proto_dot_shard__pb2.StatsReply.SerializeToString,
            ),
            'Drain': grpc.unary_unary_rpc_method_handler(
                    servicer.Drain,
                    request_deserializer=shipinfer_dot_launch_dot_proto_dot_shard__pb2.DrainRequest.FromString,
                    response_serializer=shipinfer_dot_launch_dot_proto_dot_shard__pb2.DrainReply.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=shipinfer_dot_launch_dot_proto_dot_shard__pb2.StopRequest.FromString,
                    response_serializer=shipinfer_dot_launch_dot_proto_dot_shard__pb2.StopReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shipinfer.launch.v1.Shard', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('shipinfer.launch.v1.Shard', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Shard(object):
    """The control surface a shard process exposes to its launcher.
    """

    @staticmethod
    def Ready(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shipinfer.launch.v1.Shard/Ready',
            shipinfer_dot_launch_dot_proto_dot_shard__pb2.ReadyRequest.SerializeToString,
            shipinfer_dot_launch_dot_proto_dot_shard__pb2.ReadyReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTopology(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shipinfer.launch.v1.Shard/UpdateTopology',
            shipinfer_dot_launch_dot_proto_dot_shard__pb2.TopologyRequest.SerializeToString,
            shipinfer_dot_launch_dot_proto_dot_shard__pb2.TopologyReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddCamera(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shipinfer.launch.v1.Shard/AddCamera',
            shipinfer_dot_launch_dot_proto_dot_shard__pb2.AddCameraRequest.SerializeToString,
            shipinfer_dot_launch_dot_proto_dot_shard__pb2.AddCameraReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveCamera(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shipinfer.launch.v1.Shard/RemoveCamera',
            shipinfer_dot_launch_dot_proto_dot_shard__pb2.RemoveCameraRequest.SerializeToString,
            shipinfer_dot_launch_dot_proto_dot_shard__pb2.RemoveCameraReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shipinfer.launch.v1.Shard/Health',
            shipinfer_dot_launch_dot_proto_dot_shard__pb2.HealthRequest.SerializeToString,
            shipinfer_dot_launch_dot_proto_dot_shard__pb2.HealthReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shipinfer.launch.v1.Shard/Stats',
            shipinfer_dot_launch_dot_proto_dot_shard__pb2.StatsRequest.SerializeToString,
            shipinfer_dot_launch_dot_proto_dot_shard__pb2.StatsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Drain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shipinfer.launch.v1.Shard/Drain',
            shipinfer_dot_launch_dot_proto_dot_shard__pb2.DrainRequest.SerializeToString,
            shipinfer_dot_launch_dot_proto_dot_shard__pb2.DrainReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shipinfer.launch.v1.Shard/Stop',
            shipinfer_dot_launch_dot_proto_dot_shard__pb2.StopRequest.SerializeToString,
            shipinfer_dot_launch_dot_proto_dot_shard__pb2.StopReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
