# Generated by scripts/gen_proto.py from src/shipinfer/launch/proto/shard.proto -- DO NOT EDIT.
# Regenerate with:  python scripts/gen_proto.py
from google.protobuf import struct_pb2 as _struct_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from typing import ClassVar as _ClassVar, Iterable as _Iterable, Mapping as _Mapping, Optional as _Optional, Union as _Union

DESCRIPTOR: _descriptor.FileDescriptor

class ShardIdentity(_message.Message):
    __slots__ = ("shard_id", "control_port", "pid")
    SHARD_ID_FIELD_NUMBER: _ClassVar[int]
    CONTROL_PORT_FIELD_NUMBER: _ClassVar[int]
    PID_FIELD_NUMBER: _ClassVar[int]
    shard_id: int
    control_port: int
    pid: int
    def __init__(self, shard_id: _Optional[int] = ..., control_port: _Optional[int] = ..., pid: _Optional[int] = ...) -> None: ...

class ReadyRequest(_message.Message):
    __slots__ = ()
    def __init__(self) -> None: ...

class ReadyReply(_message.Message):
    __slots__ = ("identity", "state")
    IDENTITY_FIELD_NUMBER: _ClassVar[int]
    STATE_FIELD_NUMBER: _ClassVar[int]
    identity: ShardIdentity
    state: str
    def __init__(self, identity: _Optional[_Union[ShardIdentity, _Mapping]] = ..., state: _Optional[str] = ...) -> None: ...

class TopologyRequest(_message.Message):
    __slots__ = ("chain_yaml", "shared_by", "share_rank")
    CHAIN_YAML_FIELD_NUMBER: _ClassVar[int]
    SHARED_BY_FIELD_NUMBER: _ClassVar[int]
    SHARE_RANK_FIELD_NUMBER: _ClassVar[int]
    chain_yaml: str
    shared_by: _containers.RepeatedScalarFieldContainer[int]
    share_rank: _containers.RepeatedScalarFieldContainer[int]
    def __init__(self, chain_yaml: _Optional[str] = ..., shared_by: _Optional[_Iterable[int]] = ..., share_rank: _Optional[_Iterable[int]] = ...) -> None: ...

class TopologyReply(_message.Message):
    __slots__ = ("accepted", "reason", "topology")
    ACCEPTED_FIELD_NUMBER: _ClassVar[int]
    REASON_FIELD_NUMBER: _ClassVar[int]
    TOPOLOGY_FIELD_NUMBER: _ClassVar[int]
    accepted: bool
    reason: str
    topology: str
    def __init__(self, accepted: bool = ..., reason: _Optional[str] = ..., topology: _Optional[str] = ...) -> None: ...

class CameraSpec(_message.Message):
    __slots__ = ("camera_id", "url", "fps")
    CAMERA_ID_FIELD_NUMBER: _ClassVar[int]
    URL_FIELD_NUMBER: _ClassVar[int]
    FPS_FIELD_NUMBER: _ClassVar[int]
    camera_id: str
    url: str
    fps: float
    def __init__(self, camera_id: _Optional[str] = ..., url: _Optional[str] = ..., fps: _Optional[float] = ...) -> None: ...

class AddCameraRequest(_message.Message):
    __slots__ = ("camera",)
    CAMERA_FIELD_NUMBER: _ClassVar[int]
    camera: CameraSpec
    def __init__(self, camera: _Optional[_Union[CameraSpec, _Mapping]] = ...) -> None: ...

class AddCameraReply(_message.Message):
    __slots__ = ("accepted", "reason")
    ACCEPTED_FIELD_NUMBER: _ClassVar[int]
    REASON_FIELD_NUMBER: _ClassVar[int]
    accepted: bool
    reason: str
    def __init__(self, accepted: bool = ..., reason: _Optional[str] = ...) -> None: ...

class RemoveCameraRequest(_message.Message):
    __slots__ = ("camera_id", "timeout_s")
    CAMERA_ID_FIELD_NUMBER: _ClassVar[int]
    TIMEOUT_S_FIELD_NUMBER: _ClassVar[int]
    camera_id: str
    timeout_s: float
    def __init__(self, camera_id: _Optional[str] = ..., timeout_s: _Optional[float] = ...) -> None: ...

class RemoveCameraReply(_message.Message):
    __slots__ = ("removed", "clean", "reason")
    REMOVED_FIELD_NUMBER: _ClassVar[int]
    CLEAN_FIELD_NUMBER: _ClassVar[int]
    REASON_FIELD_NUMBER: _ClassVar[int]
    removed: bool
    clean: bool
    reason: str
    def __init__(self, removed: bool = ..., clean: bool = ..., reason: _Optional[str] = ...) -> None: ...

class HealthRequest(_message.Message):
    __slots__ = ()
    def __init__(self) -> None: ...

class HealthReply(_message.Message):
    __slots__ = ("state", "engine", "cameras", "vram_budget", "detail")
    STATE_FIELD_NUMBER: _ClassVar[int]
    ENGINE_FIELD_NUMBER: _ClassVar[int]
    CAMERAS_FIELD_NUMBER: _ClassVar[int]
    VRAM_BUDGET_FIELD_NUMBER: _ClassVar[int]
    DETAIL_FIELD_NUMBER: _ClassVar[int]
    state: str
    engine: _struct_pb2.Struct
    cameras: _struct_pb2.Struct
    vram_budget: _struct_pb2.Struct
    detail: str
    def __init__(self, state: _Optional[str] = ..., engine: _Optional[_Union[_struct_pb2.Struct, _Mapping]] = ..., cameras: _Optional[_Union[_struct_pb2.Struct, _Mapping]] = ..., vram_budget: _Optional[_Union[_struct_pb2.Struct, _Mapping]] = ..., detail: _Optional[str] = ...) -> None: ...

class StatsRequest(_message.Message):
    __slots__ = ()
    def __init__(self) -> None: ...

class StatsReply(_message.Message):
    __slots__ = ("stats", "detail")
    STATS_FIELD_NUMBER: _ClassVar[int]
    DETAIL_FIELD_NUMBER: _ClassVar[int]
    stats: _struct_pb2.Struct
    detail: str
    def __init__(self, stats: _Optional[_Union[_struct_pb2.Struct, _Mapping]] = ..., detail: _Optional[str] = ...) -> None: ...

class DrainRequest(_message.Message):
    __slots__ = ("timeout_s",)
    TIMEOUT_S_FIELD_NUMBER: _ClassVar[int]
    timeout_s: float
    def __init__(self, timeout_s: _Optional[float] = ...) -> None: ...

class DrainReply(_message.Message):
    __slots__ = ("abandoned", "detail")
    ABANDONED_FIELD_NUMBER: _ClassVar[int]
    DETAIL_FIELD_NUMBER: _ClassVar[int]
    abandoned: int
    detail: str
    def __init__(self, abandoned: _Optional[int] = ..., detail: _Optional[str] = ...) -> None: ...

class StopRequest(_message.Message):
    __slots__ = ("timeout_s",)
    TIMEOUT_S_FIELD_NUMBER: _ClassVar[int]
    timeout_s: float
    def __init__(self, timeout_s: _Optional[float] = ...) -> None: ...

class StopReply(_message.Message):
    __slots__ = ("abandoned", "detail")
    ABANDONED_FIELD_NUMBER: _ClassVar[int]
    DETAIL_FIELD_NUMBER: _ClassVar[int]
    abandoned: int
    detail: str
    def __init__(self, abandoned: _Optional[int] = ..., detail: _Optional[str] = ...) -> None: ...
