#!/usr/bin/env python3
"""Regenerate the committed gRPC stubs for ``src/shipinfer/launch/proto/shard.proto``.

    python scripts/gen_proto.py            # regenerate in place
    python scripts/gen_proto.py --check    # fail if the committed stubs are stale

**Why the stubs are committed.** ``grpcio-tools`` is a build-time dependency, not a runtime
one: a wheel that generated its stubs at install time would need a protobuf compiler on every
deployment host, and an editable checkout would need one before ``import shipinfer.launch``
worked at all. Committing them is what keeps the ``grpc`` extra to two pure-runtime packages.
The cost is that a ``.proto`` edit and its stubs can drift, so
``tests/launch/test_proto_is_current.py`` regenerates into a temporary directory and diffs.

**Why ``-I src``.** ``protoc`` derives the generated cross-imports from the proto's path
*relative to the include root*. Compiled as ``shard.proto`` the grpc stub emits a top-level
``import shard_pb2``, which only resolves if the package directory happens to be on
``sys.path``; compiled as ``shipinfer/launch/proto/shard.proto`` it emits the package-relative
``from shipinfer.launch.proto import shard_pb2`` and works from anywhere. :func:`_fix_imports`
is the belt to that braces — it rewrites a bare import if a future protoc emits one, and says
so rather than silently producing a module that fails on the deployment host.
"""

from __future__ import annotations

import argparse
import filecmp
import re
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
#: The proto's path relative to the include root, which is also its identity in protobuf's
#: global descriptor pool. Keep it fully qualified: two projects that both compile a bare
#: ``shard.proto`` into one interpreter collide in that pool at import time.
PROTO = Path("shipinfer/launch/proto/shard.proto")
#: What one run produces, in the order it is reported.
GENERATED = ("shard_pb2.py", "shard_pb2.pyi", "shard_pb2_grpc.py")

#: Prepended to every generated file. protoc writes its own "DO NOT EDIT" line, but not
#: *which* command in this repository puts the file back — which is the only thing a reader
#: who has just edited the .proto actually needs.
HEADER = (
    "# Generated by scripts/gen_proto.py from"
    " src/shipinfer/launch/proto/shard.proto -- DO NOT EDIT.\n"
    "# Regenerate with:  python scripts/gen_proto.py\n"
)

#: A cross-import protoc emits when the proto was compiled from its own directory. Rewritten
#: rather than tolerated: it imports fine in a test that happens to have the directory on
#: `sys.path` and fails at start-up everywhere else.
_BARE_IMPORT = re.compile(r"^import shard_pb2 as ", re.MULTILINE)
_PACKAGE_IMPORT = "from shipinfer.launch.proto import shard_pb2 as "


def generate(out_root: Path) -> list[Path]:
    """Compile the proto into ``out_root`` and return the files written.

    Args:
        out_root: stands in for ``src/``. The stubs land under
            ``out_root/shipinfer/launch/proto/``, so a caller can generate into a temporary
            directory and compare against the committed tree.

    Raises:
        SystemExit: ``grpcio-tools`` is not installed, or protoc rejected the document. Both
            are operator-facing: this is a script, and a traceback out of ``protoc`` says less
            than its own diagnostics do.
    """
    try:
        from grpc_tools import protoc
    except ImportError:  # pragma: no cover - exercised by the operator, not the suite
        raise SystemExit(
            "scripts/gen_proto.py needs grpcio-tools: pip install -e '.[dev]'"
        ) from None

    package_dir = out_root / PROTO.parent
    package_dir.mkdir(parents=True, exist_ok=True)
    # protoc resolves `import "google/protobuf/struct.proto"` out of the copy grpcio-tools
    # ships, so a host with no system protobuf include tree still compiles this.
    well_known = Path(protoc.__file__).parent / "_proto"
    argv = [
        "protoc",
        f"-I{SRC}",
        f"-I{well_known}",
        f"--python_out={out_root}",
        f"--pyi_out={out_root}",
        f"--grpc_python_out={out_root}",
        str(SRC / PROTO),
    ]
    status = protoc.main(argv)
    if status != 0:
        raise SystemExit(f"protoc failed ({status}): {' '.join(argv)}")

    written: list[Path] = []
    for name in GENERATED:
        path = package_dir / name
        if not path.is_file():
            raise SystemExit(f"protoc did not write {path}")
        path.write_text(
            HEADER + _fix_imports(path.read_text(encoding="utf-8")), encoding="utf-8"
        )
        written.append(path)
    return written


def _fix_imports(text: str) -> str:
    """Make protoc's cross-import package-relative. A no-op when ``-I src`` did its job."""
    return _BARE_IMPORT.sub(_PACKAGE_IMPORT, text)


def _check() -> int:
    """Regenerate into a temporary tree and diff against what is committed."""
    with tempfile.TemporaryDirectory() as tmp:
        fresh = generate(Path(tmp))
        stale = [
            path.name
            for path in fresh
            if not filecmp.cmp(path, SRC / PROTO.parent / path.name, shallow=False)
        ]
    if stale:
        print(
            "stale generated stubs: " + ", ".join(stale) + "\nrun: python scripts/gen_proto.py",
            file=sys.stderr,
        )
        return 1
    print("generated stubs are current")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit non-zero if the committed stubs are stale",
    )
    args = parser.parse_args(argv)
    if args.check:
        return _check()
    for path in generate(SRC):
        print(f"wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
